// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPingService creates a new instance of MockPingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPingService {
	mock := &MockPingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPingService is an autogenerated mock type for the PingService type
type MockPingService struct {
	mock.Mock
}

type MockPingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPingService) EXPECT() *MockPingService_Expecter {
	return &MockPingService_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockPingService
func (_mock *MockPingService) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPingService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPingService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx
func (_e *MockPingService_Expecter) Ping(ctx interface{}) *MockPingService_Ping_Call {
	return &MockPingService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPingService_Ping_Call) Run(run func(ctx context.Context)) *MockPingService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPingService_Ping_Call) Return(err error) *MockPingService_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPingService_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockPingService_Ping_Call {
	_c.Call.Return(run)
	return _c
}
