root = "../.."
# testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "../../tmp/agent"
  cmd = "go build -o ../../tmp/agent ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "cmd/agent", "internal/http-server"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "IS_DEV=true ../../tmp/agent"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 300
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  enabled = false
  app_port = 8080
  proxy_port = 8000

[screen]
  clear_on_rebuild = false
  keep_scroll = true
