#:schema https://raw.githubusercontent.com/arhea/air/refs/heads/jsonschema/air.schema.json
root = "../.."
# testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "../../tmp/server"
cmd = "go build -o ../../tmp/server ."
delay = 1000
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "testdata",
  "cmd/agent",
  "internal/agent",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "IS_DEV=true RESTORE=true ../../tmp/server"
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = 500
log = "build-errors.log"
poll = false
poll_interval = 500
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 300
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = false

[proxy]
enabled = false
app_port = 8080
proxy_port = 8000

[screen]
clear_on_rebuild = false
keep_scroll = true
