// Code generated by prebuild.go; DO NOT EDIT.
package main

import "fmt"

var (
	buildVersion string
	buildDate    string
	buildCommit  string
)

func init() {
	buildVersion = "0.20"
	buildDate = "07 Jun 25 14:56 +0300"
	buildCommit = "fix(iter-19): commented crashed tests on linux"

	fmt.Println("Build version: " + buildVersion)
	fmt.Println("Build date: " + buildDate)
	fmt.Println("Build commit: " + buildCommit)
}
